M48
; DRILL file {KiCad (6.0.9)} date Sun Jul 14 21:03:08 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-14T21:03:08-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X3.3465Y-2.1654
X3.3465Y-3.3465
X3.937Y-2.1654
X4.5276Y-2.1654
X4.5276Y-3.3465
T0
M30
